### ISSUE TITLE
http://packages.libregeek.org down?

### ISSUE THREAD

**Issue by NightlyH** [mdeguzis/SteamOS-Tools#182]
Basically, http://packages.libregeek.org has the message "Account Suspended" when trying to go to it. Which in turn basically means that SteamOS-Tools itself is also not working. Will there be a fix for this soon?

**Comment by NightlyH** [comment]
I also have a dedicated server, as well as a webhost. If you need anything to get this running again please let us know!

**Comment by pierrep** [comment]
I just hit this problem too...would be great to have this back up!

**Comment by lasdem** [comment]
Still down, does anybody have a working mirror?

**Comment by mdeguzis** [comment]
Hey everyone, so sorry I have been off the radar for some time! I have until the end of today to decide (talked to support to buy me some time today) about renewal with BlueHost. I can renew for 3 months at a minimum for 50 USD so I can download my entire site until I see if I get some good change back from Tax season (US taxes). I also have the repo content locally, as I normally just do a remote `rsync` to my BlueHost remote.

Going forward, i'm open to options. Will way we can pool mirrors, use someone's hosting, or pool funds. BlueHost isn't super expensive, but still a chunk of change for me to consider.

**Comment by mdeguzis** [comment]
Also, make sure you track https://github.com/ValveSoftware/SteamOS/issues/612. The aim and the future of community provided content likely may be FlatPaks. This would solve hosting issues (as FlatHub would be a free option). It's something I want to get more serious on myself, but until SteamOS 3.0 shows some traction (I check repo.steampowered.com regularly for updates), it hasn't been high on my radar beyond my busy day-job duties.

**Comment by NightlyH** [comment]
Thanks for the reply! I myself have a Dreamhost account sitting without being used since the site I ran no longer is in operation. I'd be willing to host a mirror if needed, and as a general backup.

**Comment by oolongbrothers** [comment]
I'd be happy to chip in with with some money again to get the SteamOS-tools repo going again :)
And I'm definitely cheering for a bright Flatpak future!

**Comment by mdeguzis** [comment]
Patreon:

I'll at least see tommorow if I can add a year to give flatpak more time and others a chance to setup a mirror. If those who wish to setup a mirror can provide a temporary ssh account, I will rsync the pool to you. Just email mdeguzis@gmail.com with an and appropriate subject like like this ticket.

**Comment by mdeguzis** [comment]
I renewed for just 3 months right now to give folks some time to setup a mirror. I am totally fine maintaining the repository, but it isn't chump change for me. I typically did 3 years at a time to save the most using the bulk option. I am pretty transparent about the costs (see pateron site in this repos README).

It is my hope Flatpak becomes the future for ease of use as well (flatpaks are much easier for users as they avoid dependency issues, but they are harder to build).

**Comment by mdeguzis** [comment]
Apparently my public_html was wiped out when the renewal lapsed and I don't have the backup so i'll let you know once I've resynced local content.

**Comment by mdeguzis** [comment]
http://packages.libregeek.org/ should again be reachable for those who wish to setup a mirror. Again, any donations until such a time flatpak is more palatable and feasible instead of a Debian repo, donations are very welcome. Thank you for your patience.

**Comment by oolongbrothers** [comment]
Awesome stuff! I sent some support for the hosting your way via paypal :)
Thank you for all your great effort!

**Comment by mdeguzis** [comment]
Thank you so much! It really helps. Yes, I should get motivated soon to get back on the Flatpak train. I had talked about this once with @Plagman from Valve. I really hope that effort is still going and on the radar. It is more difficult to make Flatpaks (dependency management still has much to be desired), but it makes independence easier from several things like package conflicts and old  source packages (Debian jessie being old...). 

A good ticket to keep an eye on is https://github.com/ValveSoftware/SteamOS/issues/612. Once that is fixed, I plan to really get in gear. Bear in mind, if Valve allows FlatHub in their plans, it will include a lot of preexisting packages and not require an extra repo to host. I will use FlatHub if that is the case.

If you have any special requests @oolongbrothers , please open a ticket referencing this one and i'll try to get to it this week as a thank you. Otherwise, you have my thanks for helping out.

**Comment by oolongbrothers** [comment]
@mdeguzis Yeah, I had checked out ValveSoftware/SteamOS#612. Explains the behaviour of those Flatpaks I installed from FlatHub recently.
I can imagine that it is trickier to package Flatpaks (or Snaps for that matter), after all it's relatively new technology. But it is an awesome development for Linux. I guess the reward would be that your packing efforts would benefit a much wider community, especially if hosting on FlatHub is possible.
I'm somewhat invested in Flatpak, since I co-authored and maintain the [flatpak](https://docs.ansible.com/ansible/latest/modules/flatpak_module.html) module in the Ansible project. I might have mentioned before that I automate my Steam Machine installation using Ansible configuration management (like all the rest of my computers).

I'd be happy to help testing out any of your Flatpak packaging efforts early. Let's hope ValveSoftware/SteamOS#612 will be resolved soon :crossed_fingers: 

Thank you for the offer, no special requests at the moment, I'm happy :slightly_smiling_face:

**Comment by NightlyH** [comment]
Have sent an email about a mirror, thanks!

**Comment by dpanter** [comment]
Down again now. :(
June 4, 2019
**_Account Suspended_**

**Comment by mdeguzis** [comment]
Yea finances are not optimal right now.  I may start to just push more
effort to Flathub when I find time.

**Comment by coasternd** [comment]
> My mirror is up https://steamos.tools/ however it is untested and it defiantly won't work with the current keys, however it's ~basic functions should still work~. I will be working on it, and will keep it up for the foreseeable future.
> 
> _EDIT: I forgot to edit the deb files to correctly direct to the new domain! Please refrain from using the site until I fix this._

Hi there, I was wondering if there was any way to use your mirror yet.

**Comment by HeiseiJinx** [comment]
> _EDIT: I forgot to edit the deb files to correctly direct to the new domain! Please refrain from using the site until I fix this._

Any update on the mirror @NightlyH put up? Looks like a lot of the debs are 0 byte. I had to replace the hard drive in my Steam Machine and would have liked to set this up again. :(

**Comment by mdeguzis** [comment]
I still have all my RPMs and if SteamOS 3 comes out, it might shift to Flatpak anyway. I don't have the money to pay for hosting. I could upload / rsync items if given an upload account.

**Comment by linuxgaming** [comment]
The site seems to be dead again, and as such, it's impossible to do anything, configure-repos.sh can't download the needed .debs.

**Comment by mdeguzis** [comment]
Hi @linuxgaming , I didn't have the funds to keep the site up. I will plan on resuming efforts if Valve releases a new version of SteamOS. Until then, i'd just stick to Debian repos (cautiously). Valve may be going to to flatpaks, which would negate hosted software, as I could store extras on flathub.

**Comment by dpanter** [comment]
I'll just leave a message here. Thanks for your work guys!

If you're looking for an alternative to SteamOS, I suggest checking out [GamerOS](https://gamer-os.github.io/) and if you're looking for an updated version of AntiMicro, it has been forked to [AntiMicroX](https://github.com/AntiMicroX/antimicrox).

**Comment by oolongbrothers** [comment]
Indeed, thank you very much for all your great work with SteamOS-Tools, @mdeguzis !
We'll see what the future brings.
