### ISSUE TITLE
Are you back to working on this?

### ISSUE THREAD

**Issue by NightlyH** [mdeguzis/SteamOS-Tools#184]
I noticed you added/updated a file 9 days ago. I recently got back into working on my old Steam Machine and came across this git again. I know the site is still down (and my efforts were basically moot) but it would be interesting to know if this is a project you are going to be bringing back to life.

**Comment by mdeguzis** [comment]
I haven't been working on this in a long time due to work priorities. I still want to tinker with scripts and stuff, but largely use ChimeraOS now. If I had any time, it would probably be to get more involved with that project, but still open to this. I am also largely waiting for Valve to officially push out the general PC version of SteamOS. There is a note about this on https://help.steampowered.com/en/faqs/view/1B71-EDF2-EB6D-2BB3:

>For all the tinkerers out there, please note that this system image is not quite SteamOS 3 yet. Depending on what you try to install it on (desktop, another handheld, refrigerator, toaster), it may not work properly. SteamOS 3 proper will come out sometime after launch (and even then it may not work on your toaster).
